"""
Submission 12: PXR co-crystal Tanimoto features added to TabPFN and RF.

Sub 9 showed that Uni-Mol 3D representations broke the 2D plateau (CV 0.527 → 0.5215,
LB 0.6358 → 0.6074). This submission asks whether biology-anchored structural features
can further improve generalization to the blind analog test set.

Key addition:
- **PXR co-crystal Tanimoto** (5 features): ECFP4 Tanimoto similarity vs 56 PXR
  co-crystal ligands from the PDB (fetched via scripts/fetch_crystal_ligands.py from
  github.com/OpenADMET/pxr_xtal_re-refinement). Features appended to both RF and
  TabPFN input matrices:
    max_sim   — similarity to the closest crystal ligand
    mean_sim  — mean over all 56 crystal ligands
    std_sim   — standard deviation
    top2_sim  — 2nd-highest similarity
    top3_sim  — 3rd-highest similarity

  Rationale: these 56 ligands are experimentally confirmed binders of the exact PXR
  pocket being predicted. They encode scaffold proximity to known actives in a way
  that is orthogonal to pairwise ECFP4 self-similarity within the training set — and
  because the crystal set is fixed and publicly available, it is equally informative
  for training and blind test compounds.

Model roster (5 total, same as Sub 9):
  delta        — pairwise Δ pEC50 Chemprop, kNN-anchored inference
  chemprop_hts — HTS-pretrained Chemprop (conc-aware, 3 seeds averaged)
  tabpfn_aug   — TabPFN v2 + CheMeleon 2048→PCA(200) + 5 crystal features  [NEW]
  rf_aug       — ECFP4 + ECFP6 + MACCS + RDKit descriptors + 5 crystal features  [NEW]
  unimol       — Uni-Mol 3D transformer fine-tuned on PXR pEC50

ElasticNet OOF RAE : 0.5208  (vs 0.5215 in Sub 9)
Leaderboard RAE    : 0.5998  (rank 75/329, top 23%)
CV→LB gap          : 0.079   (narrowed from 0.086 in Sub 9; crystal features generalize)
ElasticNet coefs   : unimol=0.290, tabpfn_aug=0.264, chemprop_hts=0.257,
                     delta=0.083, rf_aug=0.051

Setup (run once before this script):
    python scripts/fetch_crystal_ligands.py   # downloads 56 co-crystal SMILES from PDB
    export HF_TOKEN=your_token_here           # optional, suppresses HF rate-limit warnings

Requires CUDA GPU and unimol_tools:
    pip install unimol_tools
    python scripts/submission12_crystal.py
"""

import gc
import logging
import os
import sys
from pathlib import Path

import numpy as np

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

sys.path.insert(0, str(Path(__file__).parent.parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("submission12")

CV_SEEDS    = [42, 7]
FINAL_SEEDS = [42, 7, 13]
DEVICE      = "cuda"  # Uni-Mol requires CUDA; change to "cpu" only for debugging

CRYSTAL_LIGANDS = "data/pxr_crystal_ligands.csv"  # generated by fetch_crystal_ligands.py


# ------------------------------------------------------------------
# PXR crystal ligand Tanimoto features
# ------------------------------------------------------------------

def build_crystal_features(smiles: list[str]) -> np.ndarray:
    """ECFP4 Tanimoto similarity to the 56 PXR co-crystal ligands.

    Returns an (n, 5) float32 array: max_sim, mean_sim, std_sim, top2_sim, top3_sim.
    """
    import pandas as pd
    from rdkit import Chem, DataStructs
    from rdkit.Chem import rdFingerprintGenerator

    gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
    crystal_df = pd.read_csv(CRYSTAL_LIGANDS)
    crystal_fps = [
        gen.GetFingerprint(mol)
        for smi in crystal_df["smiles"]
        if (mol := Chem.MolFromSmiles(smi)) is not None
    ]
    logger.info(f"Crystal ligands: {len(crystal_fps)} valid fingerprints loaded")

    features = []
    for smi in smiles:
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            features.append(np.zeros(5, dtype=np.float32))
            continue
        sims = sorted(
            DataStructs.BulkTanimotoSimilarity(gen.GetFingerprint(mol), crystal_fps),
            reverse=True,
        )
        features.append(np.array([
            sims[0]              if len(sims) > 0 else 0.0,
            float(np.mean(sims)) if len(sims) > 0 else 0.0,
            float(np.std(sims))  if len(sims) > 1 else 0.0,
            sims[1]              if len(sims) > 1 else 0.0,
            sims[2]              if len(sims) > 2 else 0.0,
        ], dtype=np.float32))

    return np.array(features, dtype=np.float32)


# ------------------------------------------------------------------
# TabPFN backed by CheMeleon PCA + extra tabular features
# ------------------------------------------------------------------

class TabPFNAugmented:
    """TabPFN v2 backed by frozen CheMeleon embeddings + extra features.

    CheMeleon (2048-dim) is PCA-compressed to 200 components. The extra
    features (crystal Tanimoto, 5-dim) are standardized and appended,
    giving the model access to biology-anchored structural signal alongside
    the learned chemical-language representation.

    CheMeleon inference runs on CPU (fast feature extractor, ~30 s/fold).
    TabPFN forward pass runs on DEVICE (GPU recommended, ~5-10 s/fold vs
    3-7 min on CPU).
    """

    def __init__(self, n_components=200, n_estimators=32,
                 device="cuda", cache_dir="data/embed_cache", random_state=42):
        self.n_components  = n_components
        self.n_estimators  = n_estimators
        self.device        = device
        self.cache_dir     = cache_dir
        self.random_state  = random_state

    def _embed(self, smiles):
        from src.models.foundation_embeddings import CheMeleonEmbedder
        return CheMeleonEmbedder(device="cpu", cache_dir=self.cache_dir).transform(smiles)

    def fit(self, smiles, y, extra_features=None):
        from sklearn.decomposition import PCA
        from sklearn.preprocessing import StandardScaler
        from tabpfn import TabPFNRegressor

        X_raw = self._embed(smiles)
        self._scaler = StandardScaler()
        X_sc = self._scaler.fit_transform(X_raw)
        n_comp = min(self.n_components, X_sc.shape[0] - 1, X_sc.shape[1])
        self._pca = PCA(n_components=n_comp, random_state=self.random_state)
        X_pca = self._pca.fit_transform(X_sc)

        if extra_features is not None:
            self._extra_scaler = StandardScaler()
            X_extra = self._extra_scaler.fit_transform(extra_features.astype(np.float64))
            X_final = np.hstack([X_pca, X_extra])
        else:
            self._extra_scaler = None
            X_final = X_pca

        self._tabpfn = TabPFNRegressor(
            n_estimators=self.n_estimators, device=self.device,
            random_state=self.random_state, ignore_pretraining_limits=True,
        )
        self._tabpfn.fit(X_final, np.asarray(y, dtype=np.float32))
        logger.info(f"TabPFNAugmented.fit: {X_final.shape[1]} total features")
        return self

    def predict(self, smiles, extra_features=None):
        X_pca = self._pca.transform(self._scaler.transform(self._embed(smiles)))
        if extra_features is not None and self._extra_scaler is not None:
            X_extra = self._extra_scaler.transform(extra_features.astype(np.float64))
            X_final = np.hstack([X_pca, X_extra])
        else:
            X_final = X_pca
        return self._tabpfn.predict(X_final).astype(np.float32)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def build_sample_weights(train) -> np.ndarray:
    w = (
        train["sample_weight"].values.copy()
        if "sample_weight" in train.columns
        else np.ones(len(train))
    )
    if "is_nonspecific" in train.columns:
        w[train["is_nonspecific"].values] *= 0.3
    return w.astype(np.float32)


def train_chemprop(sm_tr, y_tr, sw_tr, seed, epochs, lr, init_sd=None, x_d=None):
    from src.models.chemprop_model import ChempropModel
    m = ChempropModel(
        epochs=epochs, hidden_size=300, depth=3, ffn_num_layers=3,
        dropout=0.1, batch_size=64, lr=lr, device=DEVICE,
        snapshot_epochs=5, extra_features=False, seed=seed, n_tasks=1,
    )
    m.fit(sm_tr, y_tr, sample_weight=sw_tr, init_state_dict=init_sd, x_d=x_d)
    return m


def avg_chemprop(sm_tr, y_tr, sw_tr, sm_va, seeds, epochs, lr, init_sd=None):
    return np.mean(
        [train_chemprop(sm_tr, y_tr, sw_tr, s, epochs, lr, init_sd).predict(sm_va)
         for s in seeds], axis=0
    )


def avg_chemprop_full(sm_all, y_all, sw_all, sm_test, seeds, epochs, lr, init_sd=None):
    return np.mean(
        [train_chemprop(sm_all, y_all, sw_all, s, epochs, lr, init_sd).predict(sm_test)
         for s in seeds], axis=0
    )


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

def main():
    # ---------------------------------------------------------- #
    # 1. Load data
    # ---------------------------------------------------------- #
    from src.data.load_data import load_all_tiers, COL_SMILES, COL_PECSO
    from src.data.cliff_analysis import identify_activity_cliffs, annotate_cliff_compounds

    logger.info("Loading dataset...")
    ds = load_all_tiers(cache_dir="data/hf_cache")
    train = ds.train
    test  = ds.test
    hts   = ds.hts

    logger.info("Identifying activity cliffs...")
    cliff_pairs = identify_activity_cliffs(
        smiles=train[COL_SMILES].tolist(),
        activities=train[COL_PECSO].to_numpy(),
        sim_threshold=0.7,
        activity_threshold=1.0,
    )
    train = annotate_cliff_compounds(train, cliff_pairs)

    train_smiles   = train[COL_SMILES].tolist()
    train_y        = train[COL_PECSO].to_numpy()
    test_smiles    = test[COL_SMILES].tolist()
    train_mean     = float(train_y.mean())
    sample_weights = build_sample_weights(train)
    logger.info(f"Train: {len(train)} | Test: {len(test)} | HTS: {len(hts)}")

    # ---------------------------------------------------------- #
    # 2. Concentration-aware HTS pre-training
    # ---------------------------------------------------------- #
    from src.models.hts_pretrain import prepare_hts_concentration_data
    from src.models.chemprop_model import ChempropModel

    logger.info("\n=== Concentration-aware HTS pre-training ===")
    pt_smiles, pt_y, pt_xd = prepare_hts_concentration_data(
        hts_df=hts, primary_train=train
    )
    logger.info(f"Pre-training on {len(pt_smiles)} rows ({len(set(pt_smiles))} unique compounds)")

    pretrain_model = ChempropModel(
        epochs=60, hidden_size=300, depth=3, ffn_num_layers=3,
        dropout=0.1, batch_size=64, lr=1e-3, device=DEVICE,
        snapshot_epochs=5, extra_features=False, seed=42, n_tasks=1,
    )
    pretrain_model.fit(pt_smiles, pt_y, x_d=pt_xd)
    hts_state_dict = pretrain_model.get_state_dict()
    del pretrain_model; gc.collect()
    logger.info("HTS pre-training complete.")

    # ---------------------------------------------------------- #
    # 3. PXR crystal ligand Tanimoto features
    # ---------------------------------------------------------- #
    if not Path(CRYSTAL_LIGANDS).exists():
        raise FileNotFoundError(
            f"{CRYSTAL_LIGANDS} not found.\n"
            "Run: python scripts/fetch_crystal_ligands.py"
        )

    logger.info("\n=== Building PXR crystal ligand Tanimoto features ===")
    crystal_train = build_crystal_features(train_smiles)
    crystal_test  = build_crystal_features(test_smiles)
    logger.info(
        f"Crystal features: train={crystal_train.shape}, test={crystal_test.shape}  "
        f"(train max_sim mean={crystal_train[:, 0].mean():.3f})"
    )

    # ---------------------------------------------------------- #
    # 4. Feature matrices (RF: base fingerprints + crystal)
    # ---------------------------------------------------------- #
    from src.features.feature_engineering import ecfp4, FeaturePipeline

    logger.info("\n=== Building feature matrices ===")
    fps_train = ecfp4(train_smiles)
    fps_test  = ecfp4(test_smiles)

    pipeline = FeaturePipeline(
        include_mordred=False, include_ecfp6=True,
        include_fcfp4=False, include_maccs=True,
    )
    X_base_train = pipeline.fit_transform(train_smiles)
    X_base_test  = pipeline.transform(test_smiles)

    X_aug_train = np.hstack([X_base_train, crystal_train])
    X_aug_test  = np.hstack([X_base_test,  crystal_test])
    logger.info(f"RF features: base={X_base_train.shape[1]}  augmented={X_aug_train.shape[1]}")

    # ---------------------------------------------------------- #
    # 5. Butina 5-fold CV — OOF predictions for all models
    # ---------------------------------------------------------- #
    from src.evaluation.validate import ButinaKFold, rae
    from src.models.gbm_models import RFWrapper
    from src.models.delta_model import DeltaChempropModel
    from src.models.unimol_model import UniMolModel

    logger.info("\n=== Butina 5-fold CV ===")
    splitter = ButinaKFold(n_splits=5, tanimoto_threshold=0.4, random_state=42)
    folds    = list(splitter.split(train_smiles))

    model_names = ["delta", "chemprop_hts", "tabpfn_aug", "rf_aug", "unimol"]
    oof         = {m: np.zeros(len(train)) for m in model_names}
    fold_raes   = {m: [] for m in model_names}

    for fold, (tr_idx, va_idx) in enumerate(folds):
        logger.info(f"\n--- Fold {fold} (train={len(tr_idx)}, val={len(va_idx)}) ---")
        sm_tr      = [train_smiles[i] for i in tr_idx]
        sm_va      = [train_smiles[i] for i in va_idx]
        y_tr, y_va = train_y[tr_idx], train_y[va_idx]
        sw_tr      = sample_weights[tr_idx]
        fps_tr     = fps_train[tr_idx]
        fps_va     = fps_train[va_idx]
        fold_mean  = float(y_tr.mean())

        # Delta (HTS-initialized)
        logger.info(f"Fold {fold}: Delta model...")
        delta_cv = DeltaChempropModel(
            epochs=40, hidden_size=300, depth=3, ffn_num_layers=3,
            dropout=0.1, batch_size=64, lr=1e-3, device=DEVICE,
            snapshot_epochs=5, seed=42, n_pairs_per_epoch=20_000,
            cliff_oversample=3, k_neighbors=10,
        )
        delta_cv.fit(sm_tr, y_tr, fps_train=fps_tr, init_state_dict=hts_state_dict)
        oof["delta"][va_idx] = delta_cv.predict(sm_va, sm_tr, y_tr, fps_tr, fps_va)
        fold_raes["delta"].append(rae(y_va, oof["delta"][va_idx], y_train_mean=fold_mean))
        logger.info(f"Fold {fold}: delta RAE={fold_raes['delta'][-1]:.4f}")
        del delta_cv; gc.collect()

        # Chemprop HTS (HTS-initialized, 2 seeds averaged)
        logger.info(f"Fold {fold}: Chemprop HTS (2 seeds)...")
        oof["chemprop_hts"][va_idx] = avg_chemprop(
            sm_tr, y_tr, sw_tr, sm_va, CV_SEEDS, epochs=60, lr=5e-4, init_sd=hts_state_dict,
        )
        fold_raes["chemprop_hts"].append(
            rae(y_va, oof["chemprop_hts"][va_idx], y_train_mean=fold_mean)
        )
        logger.info(f"Fold {fold}: chemprop_hts RAE={fold_raes['chemprop_hts'][-1]:.4f}")

        # TabPFN + CheMeleon PCA + crystal features
        logger.info(f"Fold {fold}: TabPFN + CheMeleon + crystal features...")
        tabpfn_cv = TabPFNAugmented(
            n_components=200, n_estimators=32, device=DEVICE, random_state=42,
        )
        tabpfn_cv.fit(sm_tr, y_tr, extra_features=crystal_train[tr_idx])
        oof["tabpfn_aug"][va_idx] = tabpfn_cv.predict(
            sm_va, extra_features=crystal_train[va_idx]
        )
        fold_raes["tabpfn_aug"].append(
            rae(y_va, oof["tabpfn_aug"][va_idx], y_train_mean=fold_mean)
        )
        logger.info(f"Fold {fold}: tabpfn_aug RAE={fold_raes['tabpfn_aug'][-1]:.4f}")
        del tabpfn_cv; gc.collect()

        # RF + crystal features
        rf_cv = RFWrapper()
        rf_cv.fit(X_aug_train[tr_idx], y_tr, sample_weight=sw_tr)
        oof["rf_aug"][va_idx] = rf_cv.predict(X_aug_train[va_idx])
        fold_raes["rf_aug"].append(
            rae(y_va, oof["rf_aug"][va_idx], y_train_mean=fold_mean)
        )
        logger.info(f"Fold {fold}: rf_aug RAE={fold_raes['rf_aug'][-1]:.4f}")
        del rf_cv; gc.collect()

        # Uni-Mol 3D
        logger.info(f"Fold {fold}: Uni-Mol 3D (10 epochs)...")
        um = UniMolModel(epochs=10, lr=1e-4, batch_size=16, seed=42)
        um.fit(sm_tr, y_tr)
        oof["unimol"][va_idx] = um.predict(sm_va)
        fold_raes["unimol"].append(rae(y_va, oof["unimol"][va_idx], y_train_mean=fold_mean))
        logger.info(f"Fold {fold}: unimol RAE={fold_raes['unimol'][-1]:.4f}")
        del um; gc.collect()

    # ---------------------------------------------------------- #
    # 6. CV summary
    # ---------------------------------------------------------- #
    logger.info("\n=== CV Summary ===")
    for m in model_names:
        mean_r = float(np.mean(fold_raes[m]))
        std_r  = float(np.std(fold_raes[m]))
        logger.info(f"  {m:<20}: {mean_r:.4f} ± {std_r:.4f}")

    # ---------------------------------------------------------- #
    # 7. ElasticNet stacking
    # ---------------------------------------------------------- #
    from src.ensemble.stack_and_submit import ElasticNetStacker

    logger.info("\n=== ElasticNet stacking ===")
    oof_matrix = np.column_stack([oof[m] for m in model_names])
    stacker    = ElasticNetStacker(l1_ratio=0.7, cv=5)
    stacker.fit(oof_matrix, train_y, model_names=model_names)

    oof_stacked = stacker.predict(oof_matrix)
    stacked_rae = float(rae(train_y, oof_stacked, y_train_mean=train_mean))
    logger.info(f"ElasticNet OOF RAE: {stacked_rae:.4f}")
    logger.info(f"ElasticNet coefs: {stacker.coefs}")

    # ---------------------------------------------------------- #
    # 8. Full training
    # ---------------------------------------------------------- #
    logger.info("\n=== Full training (all data) ===")

    logger.info("Full training: Delta model (3 seeds)...")
    delta_preds_all = []
    for seed in FINAL_SEEDS:
        dm = DeltaChempropModel(
            epochs=50, hidden_size=300, depth=3, ffn_num_layers=3,
            dropout=0.1, batch_size=64, lr=1e-3, device=DEVICE,
            snapshot_epochs=5, seed=seed, n_pairs_per_epoch=20_000,
            cliff_oversample=3, k_neighbors=10,
        )
        dm.fit(train_smiles, train_y, fps_train=fps_train, init_state_dict=hts_state_dict)
        delta_preds_all.append(
            dm.predict(test_smiles, train_smiles, train_y, fps_train, fps_test)
        )
        del dm; gc.collect()
    test_preds_delta = np.mean(delta_preds_all, axis=0)

    logger.info("Full training: Chemprop HTS (3 seeds)...")
    test_preds_chemprop_hts = avg_chemprop_full(
        train_smiles, train_y, sample_weights, test_smiles,
        FINAL_SEEDS, epochs=80, lr=5e-4, init_sd=hts_state_dict,
    )
    del hts_state_dict; gc.collect()

    logger.info("Full training: TabPFN + CheMeleon + crystal features...")
    tabpfn_full = TabPFNAugmented(
        n_components=200, n_estimators=32, device=DEVICE, random_state=42,
    )
    tabpfn_full.fit(train_smiles, train_y, extra_features=crystal_train)
    test_preds_tabpfn = tabpfn_full.predict(test_smiles, extra_features=crystal_test)
    del tabpfn_full; gc.collect()

    logger.info("Full training: RF + crystal features...")
    rf_full = RFWrapper()
    rf_full.fit(X_aug_train, train_y, sample_weight=sample_weights)
    test_preds_rf = rf_full.predict(X_aug_test)

    logger.info("Full training: Uni-Mol 3D (20 epochs)...")
    um_full = UniMolModel(epochs=20, lr=1e-4, batch_size=16, seed=42,
                          save_path="logs/unimol_full")
    um_full.fit(train_smiles, train_y)
    test_preds_unimol = um_full.predict(test_smiles)
    del um_full; gc.collect()

    test_preds = {
        "delta":        test_preds_delta,
        "chemprop_hts": test_preds_chemprop_hts,
        "tabpfn_aug":   test_preds_tabpfn,
        "rf_aug":       test_preds_rf,
        "unimol":       test_preds_unimol,
    }
    for m, p in test_preds.items():
        logger.info(f"  {m:<20}: mean={p.mean():.3f}, std={p.std():.3f}")

    # ---------------------------------------------------------- #
    # 9. Apply stacker and save submission
    # ---------------------------------------------------------- #
    test_matrix = np.column_stack([test_preds[m] for m in model_names])
    final_preds = stacker.predict(test_matrix)
    logger.info(f"Ensemble: mean={final_preds.mean():.3f}, std={final_preds.std():.3f}")

    from src.ensemble.stack_and_submit import make_submission, validate_submission

    submission_path = make_submission(
        test_df=test,
        predictions=final_preds,
        output_dir="submissions",
    )
    logger.info(f"Submission saved to {submission_path}")

    ok = validate_submission(submission_path, test)
    if ok:
        logger.info("Submission validation PASSED.")
    else:
        logger.error("Submission validation FAILED — check output above.")


if __name__ == "__main__":
    main()
